local opt = vim.opt

opt.hlsearch = false
opt.backup = false
opt.number = true
opt.relativenumber = false
opt.cmdheight = 2
opt.ignorecase = true
opt.smartcase = true
opt.pumheight = 10
opt.showtabline = 2
opt.smartindent = true
opt.swapfile = false
opt.splitbelow = true
opt.splitright = true
opt.updatetime = 300
opt.writebackup = false
opt.expandtab = true
opt.shiftwidth = 2
opt.cursorline = false
opt.numberwidth = 4
opt.wrap = false
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.undofile = true
opt.signcolumn = "yes"
opt.showmode = false
opt.hidden = true
